#!/bin/sh -e

hsh_action=$1
sandbox_name=$2

maintainer_name="Alexander Makeenkov"
maintainer_mail="amakeenk@altlinux.org"

sandbox_dir="${HOME}/hsh-sandboxes/${sandbox_name}"
sandbox_dir_tmp="${TMP}/hsh-sandboxes/${sandbox_name}"
sandbox_dir_tmp_hasher="${sandbox_dir_tmp}/hasher"

build_arch=$(echo ${sandbox_name} | awk -F"-" '{print $3}')

if [ -z ${hsh_action} ] || [ -z ${sandbox_name} ]; then
	echo "Usage: $0 --hsh-action sandbox-name"
	echo "Where hsh-action is: build, rebuild or clean-all"
	exit 1
fi

mkdir -p ${sandbox_dir_tmp_hasher}
cp -r ${sandbox_dir}/* ${sandbox_dir_tmp}

case "${hsh_action}" in
	--build)
		gear --verbose --commit --hasher -- ${build_arch} \
			hsh --verbose --nprocs=16 --packager="${maintainer_name} <${maintainer_mail}>" \
			--target=${build_arch} --lazy-cleanup --mountpoints="/proc,/dev/pts,/sys" \
			--apt-config="${sandbox_dir_tmp}/apt.conf" "${sandbox_dir_tmp_hasher}"
	;;
	--rebuild)
		gear --verbose --commit --hasher -- ${build_arch} \
			hsh-rebuild --verbose --target=${build_arch} --mountpoints="/proc,/dev/pts,/sys" "${sandbox_dir_tmp_hasher}"
	;;
	--clean-all)
		hsh --cleanup-only "${sandbox_dir_tmp_hasher}"
	;;
	*) echo -e "ERROR: $1 is wrong option"
		exit 1
	;;
esac
