#!/bin/bash -e

hsh_action=$1
sandbox_name=$2

maintainer_name=$(git config --global --list | grep user.name | cut -d"=" -f2)
maintainer_mail=$(git config --global --list | grep user.email | cut -d"=" -f2)

sandbox_dir="${HOME}/hsh-sandboxes/${sandbox_name}"
sandbox_dir_tmp="${TMP}/hsh-sandboxes/${sandbox_name}"
sandbox_dir_tmp_hasher="${sandbox_dir_tmp}/hasher"

build_arch=$(echo ${sandbox_name} | awk -F"-" '{print $3}')

if [ -z ${hsh_action} ] || [ -z ${sandbox_name} ]; then
	echo "Usage: $0 --hsh-action [build|rebuild|clean-all] sandbox-name"
	echo "Where sandbox-name like repo-pkgname-arch"
	exit 1
fi

[ -d ${sandbox_dir} ] || sandbox_init ${sandbox_name}

mkdir -p ${sandbox_dir_tmp_hasher}
cp -r ${sandbox_dir}/* ${sandbox_dir_tmp}

case "${hsh_action}" in
	--build)
		gear --verbose --commit --hasher -- ${build_arch} \
			hsh --verbose --nprocs=16 --packager="${maintainer_name} <${maintainer_mail}>" \
			--target=${build_arch} --lazy-cleanup --mountpoints="/proc,/dev/pts,/sys" \
			--apt-config="${sandbox_dir_tmp}/apt.conf" "${sandbox_dir_tmp_hasher}"
	;;
	--rebuild)
		gear --verbose --commit --hasher -- ${build_arch} \
			hsh-rebuild --verbose --target=${build_arch} --mountpoints="/proc,/dev/pts,/sys" "${sandbox_dir_tmp_hasher}"
	;;
	--clean-all)
		hsh --cleanup-only "${sandbox_dir_tmp_hasher}"
	;;
	*) echo -e "ERROR: $1 is wrong option"
		exit 1
	;;
esac
